### ISSUE TITLE
https://discohook.jaylineko.com not sending webhooks

### ISSUE THREAD

**Issue by tobiebooth** [jaylineko/discohook#1]
**Steps to reproduce:** 

1. Enter valid webhook URL into webpage
2. Add message body
3. Hit send

**Expected result:**

Message is sent.

**Actual result:**

Nothing.

Reproducible in latest Firefox and Chrome. There are no messages in the console.

**Comment by jaylineko** [comment]
This should be fixed now, please do a hard refresh (Ctrl+Shift+R) and check again.

**Comment by rondellivey03** [comment]
I had the same issue, and after I done what you said 

> please do a hard refresh (Ctrl+Shift+R) and check again.

It started working again for me.
