### ISSUE TITLE
text-size different per theme

### ISSUE THREAD

**Issue by BannerBomb** [jaylineko/discohook#2]
In the dark theme the visualizers title is bigger but in the light theme it's smaller
light theme
![image](https://user-images.githubusercontent.com/11788894/70280723-1941fc00-1787-11ea-9805-b939c9b2556f.png)
dark theme
![image](https://user-images.githubusercontent.com/11788894/70280746-25c65480-1787-11ea-8b55-b7bd2872be59.png)

this issue is also present when using a link for the title vs no url.

On the light theme It should be bold like it shows in the dark theme image
and on both themes shouldn't have the text wrapping

**Comment by jaylineko** [comment]
It looks like your browser failed to load Discord's font

Try a hard refresh and see if the issue is fixed

**Comment by BannerBomb** [comment]
It didn't. Btw I am using Firefox Developer Edition on Ubuntu 18.04.2

**Comment by jaylineko** [comment]
I cannot seem to reproduce this on a fresh installation of Firefox developer edition, perhaps a content blocking extension is blocking the font download.

Try running Firefox without any extensions enabled (Menu > Help > Restart with Add-ons Disabled...)

**Comment by BannerBomb** [comment]
this issue seems to have resolved itself :man_shrugging:.
