### ISSUE TITLE
Add color/date picker to input fields

### ISSUE THREAD

**Issue by BannerBomb** [jaylineko/discohook#5]
Would it be possible to get a color picker for the color input box something like this would be nice 
![image](https://user-images.githubusercontent.com/11788894/71441963-c6969880-26d1-11ea-86f3-5e14ea27359b.png) and a date/time picker for the timestamp input box just to make things easier?

**Comment by jaylineko** [comment]
Hello, I have added a color picker to the color input field, it appears when the input has focus.

Date picker has low priority for now, and will come at a later date.

**Comment by jaylineko** [comment]
Timestamp input fields now have a date picker. Just like the color picker, it appears when the appropriate input field has focus.
