### ISSUE TITLE
https://discohook.jaylineko.com Some webhooks not appearing in chat

### ISSUE THREAD

**Issue by Iverdenstore** [jaylineko/discohook#6]
I have created a relatively big webhook in the generator, but it's not appearing in the chat the webhook is connected to. I tried to create a different and smaller webhook, and that worked.

**Comment by jaylineko** [comment]
Hi, Discord has a 6000 character limit per message on every text field combined. Is this perhaps what you are walking into?

**Comment by jaylineko** [comment]
@Iverdenstore can you follow up on my question please?
