### ISSUE TITLE
Add the possibility to export/import JSON.

### ISSUE THREAD

**Issue by Matou0014** [jaylineko/discohook#7]
Hello Jaylineko! I'd like to suggest adding the possibility to export a webhook JSON into a text file that I could save on my computer or into a GitHub repository and load that text file again into the editor for fast edit/use/share.

**Comment by jaylineko** [comment]
While it isn't very hard to copy and paste the JSON data (or the url) by hand, I'll consider this for a future update.

**Comment by jaylineko** [comment]
I added import and export buttons to the backup modal.
