### ISSUE TITLE
Footer icon won't show without a text

### ISSUE THREAD

**Issue by MindTooth** [jaylineko/discohook#8]
HI,

Recently used your neat solution to get a grip of Discord embeds.  Thank you!

One thing I noticed when pushing to Discord, is that when the footer text is blank, or not set, the line won't show, i.e. the icon won't show without a text.

Just wanted to drop by letting you now.  If you need anything alse, please ask.

**Comment by jaylineko** [comment]
Hey, I corrected this. If you see any other behaviour inconsistent with Discord, feel free to let me know via a new issue.
