### ISSUE TITLE
Duplicating embeds

### ISSUE THREAD

**Issue by kaymeer** [jaylineko/discohook#9]
Duplicating embeds causes the site to crash.

**Comment by jaylineko** [comment]
I fixed this a few days ago, are you using a cached version?

**Comment by kaymeer** [comment]
No clean cache and even on incognito, if i refresh the page after getting the error it works tho.
This is what I get: "TypeError: Cannot read property 'inline' of undefined"

**Comment by jaylineko** [comment]
Turns out I forgot to deploy my fix, try again?

**Comment by kaymeer** [comment]
Yes it is fixed now, appreciate it!
